language: android
jdk: oraclejdk8
script: "./gradlew build"
android:
  components:
    # The BuildTools version used by your project
    - build-tools-25.0.2
    - platform-tools
    - extra-android-m2repository
    - extra-google-android-support
    - tools

    # The SDK version used to compile your project
    - android-25
  licenses:
      - 'android-sdk-preview-license-.+'
      - 'android-sdk-license-.+'
      - 'google-gdk-license-.+'

